spring:
  datasource:
    url: jdbc:h2:~/test
    username : sa
    password :
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
jwt:
  secret-key : RnJhbWV3b3Jrc3ByaW5nQm9vdFZlcnNpb25UaHJlZUxhbmd1YWdlSmF2YURhdGFiYXNlSDJCYWNrZW5kRGV2bG9wZXJUZXN0